// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthPSO0BvAC-1VAKUBBiSIWCOD37lOUNc',
    appId: '1:888995499358:web:be8d882e2d76764b6f53cf',
    messagingSenderId: '888995499358',
    projectId: 'authentication-671b6',
    authDomain: 'authentication-671b6.firebaseapp.com',
    storageBucket: 'authentication-671b6.firebasestorage.app',
    measurementId: 'G-BFB90PF514',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlX3zWnrqu1VPOZxKcP3LKijdD9U5CsNA',
    appId: '1:888995499358:android:d1a1cd6b694758bd6f53cf',
    messagingSenderId: '888995499358',
    projectId: 'authentication-671b6',
    storageBucket: 'authentication-671b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx044Gp34E0yBGyS_NdbdJUdBd4NL1VPU',
    appId: '1:888995499358:ios:c4da5b3891a0e91d6f53cf',
    messagingSenderId: '888995499358',
    projectId: 'authentication-671b6',
    storageBucket: 'authentication-671b6.firebasestorage.app',
    iosBundleId: 'com.example.rwad2',
  );
}
